server:
  port: 9999

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

zuul:
  prefix: /api
  routes:
    rating-server:
      path: /rating-server/**
      serviceId: RATING-SERVICE

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

